#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")"

if [[ pi.cc -nt pi ]] || find ../tau -newer pi | egrep -q .; then
  time g++ -std=c++20 -O3 $(grep ^-I ../compile_flags.txt) \
           -g pi.cc -o pi -lboost_context
fi

time ./lazytest *.md | bash
