#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")"

make()
{
  if [[ $1.cc -nt $1 ]] \
       || [[ run -nt $1 ]] \
       || find ../tau -newer $1 | egrep -q .; then
    time g++ -std=c++20 -O3 $(grep ^-I ../compile_flags.txt) \
         -g $1.cc -o $1 -lboost_context
  fi
}


make pi &
make zeta &
make pi-gc &
wait

time ./lazytest *.md | bash
