#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")"

if [[ pi0.cc -nt pi0 ]] || find ../tau -newer pi0 | egrep -q .; then
  time g++ -std=c++20 -O0 $(grep ^-I ../compile_flags.txt) \
           -g pi0.cc -o pi0 \
           -lpangocairo-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz -lcairo \
           -lxcb -lX11 -lGL -lX11-xcb \
           -lboost_context
fi

./lazytest *.md | bash
