#!/bin/bash
if [[ "$USER" != spencertipping ]]; then
  echo 'this script only works for spencer'
  exit 1
fi

CD_EXTENSIONS=( encfs )
. ~/.bash/cd/cd

cd "$(dirname "$0")"
git push

if [[ -f .git ]]; then
  cd `ni .git p'/(\S+)\/.git/'`
fi

points=( rorbot.35:tau/
         reichenbach.35:tau/
         rorbot.35:/mnt/v1/st/tau/
         orange.35:tau/
         joyce@iya.35:.spencer/tau/
         ubuntu@dev.spencertipping.com:tau/ )

for p in "${points[@]}"; do
  ( ssh "${p%%:*}" mkdir -p "${p#*:}"
    rsync -aP --delete .encfs6.xml "$p/" ) &
done

git fsck --full --strict || exit $?
git commit-graph verify || exit $?
cd renc:. || exit $?

for p in "${points[@]}"; do
  ( ssh "${p%%:*}" mkdir -p "${p#*:}"
    rsync -aP --delete 4raOSMRmHnWJJlJS7,6Zgd,I "$p/" ) &
done
wait

git push github
