#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")"

which=${1:-zeta}

exec \
  dev/emsdk em++ -Wno-parentheses -Wno-shift-count-overflow \
                 -std=c++20 -fexceptions -O3 -sASYNCIFY try/$which.cc -o try/$which.js
