#!/bin/bash
# Build the tau compiler by concatenating pieces.

set -euo pipefail
cd "$(dirname "$0")"


pm() {
  echo "BEGIN {"
  echo "#line 1 \"tau::$1\""
  cat $1
  echo "}"
}


rm -f tau

{
  cat p/head
  pm p/map.pm
  pm p/peg2.pm
  pm p/grammar.pm
  pm p/compile.pm
} > tau

chmod 0555 tau
