#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")"

#cflags="$(<compile_flags.txt) -O3"
cflags="$(grep -v ^-I compile_flags.txt) -O3"

linux_flags="$cflags -flto"
wasm_flags="$cflags -std=c++20 -fexceptions"

linux_link=(
  #-lpangocairo-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0
  #-lharfbuzz -lcairo
  #-lxcb -lX11 -lGL -lX11-xcb
  -flto
  -lboost_context
  -lzstd
)
wasm_link=(
  -sTOTAL_MEMORY=1024MB
  -sASYNCIFY
)


build_linux=yes
build_wasm=yes

while (( $# )); do
  case $1 in
    --no-wasm)  build_wasm=;  shift ;;
    --no-linux) build_linux=; shift ;;
    *) break ;;
  esac
done


mkdir -p bin/{linux,wasm}/{tau,try}


h_files=( tau.hh `find tau     -name '*.hh'` )
c_files=(        `find tau try -name '*.cc'` )
o_files=(        `find bin     -name '*.o'` )


rebuild_all=
for f in ${h_files[*]} build; do
  for o in ${o_files[*]}; do
    if [[ $f -nt $o ]]; then
      find bin -name '*.o' -delete
      rebuild_all=yes
      break
    fi
  done
done


linux_cc()
{
  src=$1
  obj=bin/linux/${src%.cc}.o
  if [[ -n $rebuild_all ]] || [[ $src -nt $obj ]]; then
    g++ $linux_flags $src -c -o $obj
    echo "linux/compiled $src"
  fi
}

wasm_cc()
{
  src=$1
  obj=bin/wasm/${src%.cc}.o
  if [[ -n $rebuild_all ]] || [[ $src -nt $obj ]]; then
    dev/emsdk em++ $wasm_flags $src -c -o $obj
    echo "wasm/compiled $src"
  fi
}


linux_link()
{
  src=$1
  obj=bin/linux/${src%.cc}.o
  out=bin/$(basename $src .cc)

  build=
  for f in $obj `find bin/linux/tau -name '*.o'`; do
    if [[ $f -nt $out ]]; then
      build=yes
      break
    fi
  done

  if [[ -n $build ]]; then
    g++ $linux_flags $obj -o $out bin/tau-linux.a ${linux_link[@]}
    echo "linux/link $out"
  fi
}

wasm_link()
{
  src=$1
  obj=bin/wasm/${src%.cc}.o
  out=bin/$(basename $src .cc).js

  build=
  for f in $obj `find bin/wasm/tau -name '*.o'`; do
    if [[ $f -nt $out ]]; then
      build=yes
      break
    fi
  done

  if [[ -n $build ]]; then
    dev/emsdk em++ $wasm_flags $obj -o $out bin/tau-wasm.a ${wasm_link[@]}
    echo "wasm/link $out"
  fi
}


compile()
{
  for f in ${c_files[*]}; do
    [[ -n $build_linux ]] && linux_cc $f &
    [[ -n $build_wasm  ]] && wasm_cc  $f &
  done
  wait
  rm -f bin/*.a
  [[ -n $build_linux ]] && ar             rcs bin/tau-linux.a `find bin/linux/tau -name '*.o'`
  [[ -n $build_wasm  ]] && dev/emsdk emar rcs bin/tau-wasm.a  `find bin/wasm/tau  -name '*.o'`
  echo "compile done"
}


link()
{
  for f in `find try -name '*.cc'`; do
    [[ -n $build_linux ]] && linux_link $f &
    [[ -n $build_wasm  ]] && wasm_link  $f &
  done
  wait
  echo "link done"
}


local_build()
{
  compile
  link
}


server_build()
{
  host=$1
  path=$2
  ssh $host mkdir -p $path
  rsync -a --delete tau.hh tau try build $host:$path/
  args=
  [[ -z $build_linux ]] && args="$args --no-linux"
  [[ -z $build_wasm  ]] && args="$args --no-wasm"
  ssh -t $host "cd $path && ./build $args"
  rsync -a --delete $host:$path/bin ./
}


case ${1:-} in
  --server)
    time server_build set.128 /nvme/asqi/tau
    ;;

  *)
    time local_build
    ;;
esac
