#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")"

./build "$@"
bin/eta0
bin/xi
bin/psi
sha1=$(bin/tau cat < README.md | sha256sum)
sha2=$(cat README.md | sha256sum)

if [[ $sha1 != $sha2 ]]; then
  echo -e "\033[1;31mbin/tau cat corrupts data\033[0;0m"
  echo
  exit 1
fi

echo
echo -e "\033[1;32mall passed\033[0;0m"
echo
