#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")"


test_sha()
{
  echo -n "testing $@... "
  local sha1=$("$@" | cat                   | sha256sum); echo -n "1"
  local sha2=$("$@" | bin/tau cat           | sha256sum); echo -n "2"
  local sha3=$("$@" | bin/tau cat2          | sha256sum); echo -n "3"
  local sha4=$("$@" | bin/phi nrun '«»'     | sha256sum); echo -n "4"
  local sha5=$("$@" | bin/phi nrun '«π:y»'  | sha256sum); echo -n "5"
  local sha6=$("$@" | bin/phi nrun '«∷[π:y⍝]»' | sha256sum); echo -n "6"
  local sha7=$("$@" | bin/tau exec /bin/cat | sha256sum); echo -n "7"
  echo

  if [[ $sha2 != $sha1 ]]; then
    echo -e "\033[1;31mbin/tau cat corrupts data from $@\033[0;0m"
    echo
    exit 1
  fi

  if [[ $sha3 != $sha1 ]]; then
    echo -e "\033[1;31mbin/tau cat2 corrupts data from $@\033[0;0m"
    echo
    exit 1
  fi

  if [[ $sha4 != $sha1 ]]; then
    echo -e "\033[1;31mbin/phi nrun «» corrupts data from $@\033[0;0m"
    echo
    exit 1
  fi

  if [[ $sha5 != $sha1 ]]; then
    echo -e "\033[1;31mbin/phi nrun «π:y» corrupts data from $@\033[0;0m"
    echo
    exit 1
  fi

  if [[ $sha6 != $sha1 ]]; then
    echo -e "\033[1;31mbin/phi nrun «∷[π:y⍝]» corrupts data from $@\033[0;0m"
    echo
    exit 1
  fi

  if [[ $sha7 != $sha1 ]]; then
    echo -e "\033[1;31mbin/tau exec /bin/cat corrupts data from $@\033[0;0m"
    echo
    exit 1
  fi
}


./build "$@"
bin/eta0
bin/xi
bin/psi

test_sha cat README.md
test_sha tar -c .git

sha_files=( README.md tau.hh `find tau -type f | sort` )

normal_sha=$(echo ${sha_files[@]} | xargs cat | sha256sum)
xcat_sha=$(  echo ${sha_files[@]} | bin/tau xcat | sha256sum)

if [[ $xcat_sha != $normal_sha ]]; then
  echo -e "\033[1;31mbin/tau xcat corrupts data\033[0;0m"
  echo
  exit 1
fi

if [[ $(bin/phi "ι↑100»'" | ni ,sr+1) != 4950 ]]; then
  echo -e '\033[1;31mbin/phi ι↑100» returned '$(bin/phi "ι↑100" | ni ,sr+1)'\033[0;0m'
  echo
  exit 1
fi


./lazytest README.md `find doc -name '*.md'` | bash


echo
echo -e "\033[1;32mall passed\033[0;0m"
echo
