#!/bin/bash
set -euo pipefail

if [[ -d /opt/emsdk/upstream/emscripten ]]; then
  # Use local versions
  cmd=$1
  shift
  exec /opt/emsdk/upstream/emscripten/$cmd "$@"
else
  # Delegate to docker
  mkdir -p /tmp/emsdk-cache
  exec docker run \
    --rm \
    -v /tmp/emsdk-cache:/emsdk/upstream/emscripten/cache \
    -v $(pwd):/src \
    -u $(id -u):$(id -g) \
    registry.128:5000/asqi/emsdk2 "$@"
fi
