#!/usr/bin/env python3
from time import time

def iota():
    for i in range(1 << 24):
        yield i

start = time()
sum = 0
for i in iota():
    sum += i
end = time()

print(f'sum = {sum}')
print(f'summed 16M ints in {(end - start) / (1 << 24) * 1e9} ns/element')
