#!/usr/bin/env python3
from time import time


xs = []
start = time()
for i in range(1 << 24):
  xs.append(i)
end = time()
print(f"prepare 16M = {end - start}s")


start = time()
t = 0
for x in xs:
  t += x
end = time()
print(f"total 16M = {t}, duration = {end - start}s")


start = time()
del xs
end = time()
print(f"delete 16M = {end - start}s")


xs = []
start = time()
for i in range(1 << 24):
  xs.append({'x': 1, 'y': i})
end = time()
print(f"prepare 16M dicts = {end - start}s")


start = time()
t = 0
for x in xs:
  t += x['y']
end = time()
print(f"total 16M dicts = {t}, duration = {end - start}s")


start = time()
del xs
end = time()
print(f"delete 16M dicts = {end - start}s")
