#!/usr/bin/env python3
from time import time

def iota():
    for i in range(1 << 24):
        yield i

t1 = time()
sum = 0
for i in iota():
    sum += i
t2 = time()

print(f'sum = {sum}')
print(f'summed 16M ints in {t2 - t1}s')