#!/usr/bin/env python3
from time import time
xs = []
for i in range(1 << 24):
  xs.append(i)

start = time()
t = 0
for x in xs:
  t += x
end = time()

print(f"total = {t}, duration = {end - start}s")
